name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "latest"
      - name: Install dependencies with Poetry
        # poetry setuptools workaround sourced from https://github.com/python-poetry/poetry/issues/7611#issuecomment-1711443539
        run: |
          poetry --version
          poetry self add setuptools
          poetry install
      - name: Run pre-commit
        run: poetry run pre-commit run --show-diff-on-failure --color=always --all-files
      # - name: Run mypy
      #   run: poetry run mypy --install-types --non-interactive --show-error-codes .
      - name: Run tests with pytest
        run: poetry run pytest tests/ --cov=buildingid --cov-report=xml --cov-report=term-missing
